apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-go
  labels:
    app: hello-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: "hello-go"
    spec:
      containers:
      - name: "hello-go"
        image: marioalbuquerque/hello-go:latest
