apiVersion: v1
kind: Service
metadata:
  name: hello-go-service
spec:
  selector:
    app: hello-go
  type: ClusterIP
  ports:
  - name: hello-go-service
    port: 80 # A porta que o serviço está escutando
    targetPort: 8000 # A porta que o container está escutando
    protocol: TCP
